/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Lightweight git probe response for the web UI.
 * @export
 * @interface GitInfo
 */
export interface GitInfo {
    /**
     * Whether work_dir is inside a git repository
     * @type {boolean}
     * @memberof GitInfo
     */
    isGitRepo: boolean;
    /**
     * 
     * @type {string}
     * @memberof GitInfo
     */
    gitRoot?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GitInfo
     */
    currentBranch?: string | null;
    /**
     * Local branch names
     * @type {Array<string>}
     * @memberof GitInfo
     */
    branches?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GitInfo
     */
    headSha?: string | null;
}

/**
 * Check if a given object implements the GitInfo interface.
 */
export function instanceOfGitInfo(value: object): value is GitInfo {
    if (!('isGitRepo' in value) || value['isGitRepo'] === undefined) return false;
    return true;
}

export function GitInfoFromJSON(json: any): GitInfo {
    return GitInfoFromJSONTyped(json, false);
}

export function GitInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'isGitRepo': json['is_git_repo'],
        'gitRoot': json['git_root'] == null ? undefined : json['git_root'],
        'currentBranch': json['current_branch'] == null ? undefined : json['current_branch'],
        'branches': json['branches'] == null ? undefined : json['branches'],
        'headSha': json['head_sha'] == null ? undefined : json['head_sha'],
    };
}

export function GitInfoToJSON(json: any): GitInfo {
    return GitInfoToJSONTyped(json, false);
}

export function GitInfoToJSONTyped(value?: GitInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_git_repo': value['isGitRepo'],
        'git_root': value['gitRoot'],
        'current_branch': value['currentBranch'],
        'branches': value['branches'],
        'head_sha': value['headSha'],
    };
}

