/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Update YOLO mode request.
 * @export
 * @interface UpdateYoloRequest
 */
export interface UpdateYoloRequest {
  /**
   * Enable or disable YOLO mode
   * @type {boolean}
   * @memberof UpdateYoloRequest
   */
  enabled: boolean;
}

/**
 * Check if a given object implements the UpdateYoloRequest interface.
 */
export function instanceOfUpdateYoloRequest(
  value: object,
): value is UpdateYoloRequest {
  if (!("enabled" in value) || value["enabled"] === undefined) return false;
  return true;
}

export function UpdateYoloRequestFromJSON(json: any): UpdateYoloRequest {
  return UpdateYoloRequestFromJSONTyped(json, false);
}

export function UpdateYoloRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateYoloRequest {
  if (json == null) {
    return json;
  }
  return {
    enabled: json["enabled"],
  };
}

export function UpdateYoloRequestToJSON(
  value?: UpdateYoloRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    enabled: value["enabled"],
  };
}
