/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * YOLO (auto-approve) mode status.
 * @export
 * @interface YoloStatus
 */
export interface YoloStatus {
  /**
   * Whether YOLO mode is enabled
   * @type {boolean}
   * @memberof YoloStatus
   */
  enabled: boolean;
  /**
   * List of auto-approved action types
   * @type {Array<string>}
   * @memberof YoloStatus
   */
  autoApproveActions?: Array<string>;
}

/**
 * Check if a given object implements the YoloStatus interface.
 */
export function instanceOfYoloStatus(
  value: object,
): value is YoloStatus {
  if (!("enabled" in value) || value["enabled"] === undefined) return false;
  return true;
}

export function YoloStatusFromJSON(json: any): YoloStatus {
  return YoloStatusFromJSONTyped(json, false);
}

export function YoloStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): YoloStatus {
  if (json == null) {
    return json;
  }
  return {
    enabled: json["enabled"],
    autoApproveActions:
      json["auto_approve_actions"] == null
        ? undefined
        : json["auto_approve_actions"],
  };
}

export function YoloStatusToJSON(value?: YoloStatus | null): any {
  if (value == null) {
    return value;
  }
  return {
    enabled: value["enabled"],
    auto_approve_actions: value["autoApproveActions"],
  };
}
