export class IncompatibleVersionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'IncompatibleVersionError';
  }
}

export class UnknownRecordTypeError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'UnknownRecordTypeError';
  }
}

export class JsonParseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'JsonParseError';
  }
}

export class WireJournalCorruptError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'WireJournalCorruptError';
  }
}

/** Lifecycle states under which `JournalWriter.append` is rejected (§5.8.2). */
export type LifecycleGatedState = 'compacting' | 'completing';

export class JournalGatedError extends Error {
  readonly state: LifecycleGatedState;
  readonly recordType: string;

  constructor(state: LifecycleGatedState, recordType: string, message?: string) {
    super(
      message ??
        `wire.jsonl write rejected: lifecycle state is "${state}" (record type: ${recordType})`,
    );
    this.name = 'JournalGatedError';
    this.state = state;
    this.recordType = recordType;
  }
}

/**
 * Phase 22 — wire generated by an incompatible producer.
 *
 * Raised by `replayWire` after the metadata header is parsed:
 *   - `producerKind='legacy'` + `reason='metadata-missing-producer'` when
 *     the header predates Phase 22 (no `producer` field).
 *   - `producerKind='python' | 'unknown'` +
 *     `reason='cross-producer-not-supported'` when the header names a
 *     producer other than `typescript`.
 *
 * `SessionManager.resumeSession` lets this error bubble up *unwrapped* so
 * the host can match it via `instanceof` and render a precise migration
 * prompt (see `migrationHint`).
 */
export class UnsupportedProducerError extends Error {
  readonly producerKind: 'python' | 'legacy' | 'unknown';
  readonly reason: 'metadata-missing-producer' | 'cross-producer-not-supported';
  readonly migrationHint: string;

  constructor(
    producerKind: 'python' | 'legacy' | 'unknown',
    reason: 'metadata-missing-producer' | 'cross-producer-not-supported',
    migrationHint: string = 'This session was created by an incompatible kimi-cli version and cannot be resumed here. Use the matching version of kimi-cli (e.g. the Python build) to continue this session.',
  ) {
    super(
      reason === 'metadata-missing-producer'
        ? `This session has no producer metadata (pre-Phase-22 wire). ${migrationHint}`
        : `This session was created by ${producerKind} kimi-cli, which is not supported by the TypeScript runtime. ${migrationHint}`,
    );
    this.name = 'UnsupportedProducerError';
    this.producerKind = producerKind;
    this.reason = reason;
    this.migrationHint = migrationHint;
  }
}
