export class IncompatibleVersionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'IncompatibleVersionError';
  }
}

export class UnknownRecordTypeError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'UnknownRecordTypeError';
  }
}

export class JsonParseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'JsonParseError';
  }
}

export class WireJournalCorruptError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'WireJournalCorruptError';
  }
}

/** Lifecycle states under which `JournalWriter.append` is rejected (§5.8.2). */
export type LifecycleGatedState = 'compacting' | 'completing';

export class JournalGatedError extends Error {
  readonly state: LifecycleGatedState;
  readonly recordType: string;

  constructor(state: LifecycleGatedState, recordType: string, message?: string) {
    super(
      message ??
        `wire.jsonl write rejected: lifecycle state is "${state}" (record type: ${recordType})`,
    );
    this.name = 'JournalGatedError';
    this.state = state;
    this.recordType = recordType;
  }
}

/**
 * Phase 22 — wire generated by an incompatible producer.
 *
 * Raised by `replayWire` after the metadata header is parsed:
 *   - `producerKind='legacy'` + `reason='metadata-missing-producer'` when
 *     the header predates Phase 22 (no `producer` field).
 *   - `producerKind='python' | 'unknown'` +
 *     `reason='cross-producer-not-supported'` when the header names a
 *     producer other than `typescript`.
 *
 * `SessionManager.resumeSession` lets this error bubble up *unwrapped* so
 * the host can match it via `instanceof` and render a precise migration
 * prompt (see `migrationHint`).
 */
export class UnsupportedProducerError extends Error {
  readonly producerKind: 'python' | 'legacy' | 'unknown';
  readonly reason: 'metadata-missing-producer' | 'cross-producer-not-supported';
  readonly migrationHint: string;

  constructor(
    producerKind: 'python' | 'legacy' | 'unknown',
    reason: 'metadata-missing-producer' | 'cross-producer-not-supported',
    migrationHint: string = 'This session was created by an incompatible kimi-cli version and cannot be resumed here. Use the matching version of kimi-cli (e.g. the Python build) to continue this session.',
  ) {
    super(
      reason === 'metadata-missing-producer'
        ? `This session has no producer metadata (pre-Phase-22 wire). ${migrationHint}`
        : `This session was created by ${producerKind} kimi-cli, which is not supported by the TypeScript runtime. ${migrationHint}`,
    );
    this.name = 'UnsupportedProducerError';
    this.producerKind = producerKind;
    this.reason = reason;
    this.migrationHint = migrationHint;
  }
}

/**
 * Phase 23 — wire.jsonl structural contract violation.
 *
 * Raised when the file-level shape disagrees with the v2 §4.1.2 physical
 * row contract after metadata/producer have been validated:
 *   - `session-initialized-missing` — line 2 is absent, is not a
 *     `session_initialized` record, or fails zod parse.
 *   - `session-initialized-position-wrong` — a `session_initialized` appears
 *     outside line 2 (e.g. duplicated mid-body).
 *   - `agent-type-mismatch` — caller expected a main wire but line 2 has
 *     `agent_type='sub'` (or vice-versa). Raised by `resumeSession` /
 *     subagent recovery, not by `replayWire` itself.
 */
export class MalformedWireError extends Error {
  readonly reason:
    | 'session-initialized-missing'
    | 'session-initialized-position-wrong'
    | 'agent-type-mismatch';
  readonly detail: string;

  constructor(
    reason:
      | 'session-initialized-missing'
      | 'session-initialized-position-wrong'
      | 'agent-type-mismatch',
    detail: string,
  ) {
    super(`Wire file structure invalid (${reason}): ${detail}`);
    this.name = 'MalformedWireError';
    this.reason = reason;
    this.detail = detail;
  }
}

/**
 * Phase 25 K0 (slice 25c-4b) — marker error thrown by every
 * `BaseContextState.appendXxx` method once `markBroken(reason)` has
 * been called (typically by JournalWriter.onPersistError wiring).
 * Callers receiving this should abort the current turn — the WAL
 * is no longer durable and any further mirror mutation would leave
 * the session in a non-replayable state.
 */
export class ContextStateBrokenError extends Error {
  // Narrow the inherited `Error.cause: unknown` (ES2022) to `Error | undefined`
  // so callers can access `err.cause` without an unsafe `as { cause?: unknown }`
  // cast. Matches the PROGRESS.md §K0 interface promise.
  override readonly cause?: Error;
  constructor(message: string, cause?: Error | undefined) {
    super(message, cause !== undefined ? { cause } : undefined);
    this.name = 'ContextStateBrokenError';
    if (cause !== undefined) {
      this.cause = cause;
    }
  }
}
