/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GitInfo,
  HTTPValidationError,
} from '../models/index';
import {
    GitInfoFromJSON,
    GitInfoToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetGitInfoApiGitInfoGetRequest {
    workDir: string;
}

/**
 * 
 */
export class GitApi extends runtime.BaseAPI {

    /**
     * Return git repo info for the given work_dir.
     * Probe a directory for git info
     */
    async getGitInfoApiGitInfoGetRaw(requestParameters: GetGitInfoApiGitInfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GitInfo>> {
        if (requestParameters['workDir'] == null) {
            throw new runtime.RequiredError(
                'workDir',
                'Required parameter "workDir" was null or undefined when calling getGitInfoApiGitInfoGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workDir'] != null) {
            queryParameters['work_dir'] = requestParameters['workDir'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/git/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GitInfoFromJSON(jsonValue));
    }

    /**
     * Return git repo info for the given work_dir.
     * Probe a directory for git info
     */
    async getGitInfoApiGitInfoGet(requestParameters: GetGitInfoApiGitInfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GitInfo> {
        const response = await this.getGitInfoApiGitInfoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
