"""Regression tests for the /init meta command."""

from __future__ import annotations

from dataclasses import replace

import pytest
from kosong.message import TextPart

from kimi_cli.soul.agent import Agent
from kimi_cli.soul.context import Context
from kimi_cli.soul.kimisoul import KimiSoul
from kimi_cli.soul.toolset import KimiToolset
from kimi_cli.ui.shell.metacmd import init as init_meta_command


@pytest.mark.asyncio
async def test_init_refreshes_runtime_agents_md(runtime, temp_work_dir):
    """Ensure `/init` reloads AGENTS.md into the runtime cache."""

    runtime_without_agents = replace(runtime, agents_md="")
    context = Context(temp_work_dir / "history.jsonl")
    agent = Agent(
        name="Test Agent",
        system_prompt="You are a test agent",
        toolset=KimiToolset(),
    )
    soul = KimiSoul(agent, runtime_without_agents, context=context)

    generated_agents_md = "Generated by /init"

    class DummyApp:
        def __init__(self, soul: KimiSoul):
            self.soul = soul

        async def _run_soul_command(self, *_args, **_kwargs):
            agents_path = self.soul._runtime.session.work_dir / "AGENTS.md"
            agents_path.write_text(generated_agents_md, encoding="utf-8")
            return True

    app = DummyApp(soul)

    await init_meta_command(app, [])

    assert app.soul._runtime.agents_md == generated_agents_md
    assert app.soul._initial_context_prepared is False

    await app.soul._ensure_initial_system_messages()

    assert app.soul._initial_context_prepared is True
    assert len(app.soul.context.history) == 2
    agents_message = app.soul.context.history[-1]
    assert agents_message.role == "assistant"
    assert isinstance(agents_message.content, list)
    assert any(
        isinstance(part, TextPart) and generated_agents_md in part.text
        for part in agents_message.content
    )
