/**
 * Hero-name slug generation — Phase 18 Section D.1 tests.
 *
 * Pins the `generatePlanSlug` contract (to be implemented in
 * `src/storage/plan-slugs.ts`). The slug:
 *   - is a hyphen-joined triple from HERO_NAMES
 *   - uses secure randomness (≥ 230 candidate names, see Python
 *     `src/kimi_cli/tools/plan/heroes.py`)
 *   - is cached per-session (second call returns the same slug)
 *   - on 20+ consecutive collisions with `existingSlugs`, appends the
 *     first 8 characters of sessionId as a tiebreaker
 *
 * RED until the module exists.
 */

import { describe, expect, it } from 'vitest';

// Module added in Phase 18 D.1 implementation.
import {
  HERO_NAMES,
  generatePlanSlug,
  __resetPlanSlugCache,
} from '../../src/storage/plan-slugs.js';

type GenerateFn = (sessionId: string, existingSlugs: Set<string>) => string;
const gen = generatePlanSlug as GenerateFn;

describe('HERO_NAMES', () => {
  it('contains at least 230 hero names (matches Python heroes.py)', () => {
    expect(Array.isArray(HERO_NAMES)).toBe(true);
    expect((HERO_NAMES as readonly string[]).length).toBeGreaterThanOrEqual(230);
  });

  it('uses kebab-case slugs (lowercase + hyphens only)', () => {
    for (const n of HERO_NAMES as readonly string[]) {
      expect(n).toMatch(/^[a-z0-9]+(-[a-z0-9]+)*$/);
    }
  });

  it('has no duplicate entries', () => {
    const set = new Set(HERO_NAMES as readonly string[]);
    expect(set.size).toBe((HERO_NAMES as readonly string[]).length);
  });
});

describe('generatePlanSlug — basic generation', () => {
  beforeEachResetCache();

  it('returns a slug made of exactly 3 hero names joined by "-"', () => {
    const slug = gen('ses_0001', new Set());
    const parts = slug.split('-');
    // Heroes themselves may contain hyphens (e.g. "iron-man"); the slug
    // is three names joined by "-" so part count is at least 3 and each
    // contiguous hero comes from HERO_NAMES.
    expect(parts.length).toBeGreaterThanOrEqual(3);
    // Recompose: slug must match HERO-HERO-HERO grammar
    const heroPattern = (HERO_NAMES as readonly string[]).map((n) => n.replaceAll('-', '\\-')).join('|');
    const re = new RegExp(`^(${heroPattern})-(${heroPattern})-(${heroPattern})$`);
    expect(slug).toMatch(re);
  });

  it('caches the slug per sessionId (second call returns the same slug)', () => {
    const s1 = gen('ses_cache_1', new Set());
    const s2 = gen('ses_cache_1', new Set());
    expect(s1).toBe(s2);
  });

  it('returns likely-distinct slugs for different sessions', () => {
    const slugs = new Set<string>();
    for (let i = 0; i < 20; i++) {
      slugs.add(gen(`ses_distinct_${i.toString()}`, new Set()));
    }
    // With 230+ names and 3-name combinations, 20 sessions should almost
    // certainly produce at least 10 unique slugs. (Probability of massive
    // collisions here is cosmically small.)
    expect(slugs.size).toBeGreaterThan(10);
  });
});

describe('generatePlanSlug — collision handling', () => {
  beforeEachResetCache();

  it('appends the first 8 chars of sessionId when every 3-name combo collides', () => {
    // Construct a pathological existingSlugs that "covers" every possible
    // 3-name combination by including a wildcard-ish collision behaviour:
    // we can't enumerate HERO_NAMES^3 slugs in a test, so we simulate the
    // fallback by making the random attempts always collide via a
    // deterministic-collision guard. Implementations compliant with Python
    // heroes.py retry 20 times; pass a `Set` of 20 specific slugs that
    // would be generated by a deterministic RNG — but since we can't
    // influence RNG here, we instead verify the contract by passing a
    // universal-match predicate via the existingSlugs parameter.
    //
    // Compliant implementations MUST expose a retry limit so that, in the
    // worst case (existingSlugs matches on every attempt), the returned
    // slug ends with `-<sessionId first 8 chars>`.
    const sessionId = 'sess_abcdefgh_XXXX';
    // "Universal-match" Set: we subclass to always report `has() === true`
    // (regardless of the passed slug). This triggers the retry fallback
    // without needing to know the RNG output.
    const universal = new (class extends Set<string> {
      override has(_v: string): boolean {
        return true;
      }
    })();
    const slug = gen(sessionId, universal as unknown as Set<string>);
    // Expected suffix = first 8 chars of sessionId
    expect(slug).toMatch(/-sess_abc$/);
  });

  it('does NOT append the session suffix when no collisions occur', () => {
    const slug = gen('ses_clean_1', new Set());
    // suffix is exactly 8 chars starting with "ses_clea" for this session
    expect(slug.endsWith('-ses_clea')).toBe(false);
  });
});

// ── Helper: cache reset between describe blocks ──────────────────────
// Phase 18 D.1 exports `__resetPlanSlugCache` so tests can isolate
// cache state. Using a plain function rather than afterEach so the
// describe blocks above read clean.
function beforeEachResetCache(): void {
  const maybeReset = __resetPlanSlugCache as unknown;
  if (typeof maybeReset === 'function') {
    (maybeReset as () => void)();
  }
}
