name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          # - runner: ubuntu-22.04-arm
          #   target: aarch64-unknown-linux-gnu
          # - runner: macos-13
          #   target: x86_64-apple-darwin
          # - runner: macos-14
          #   target: aarch64-apple-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          allow-prereleases: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "0.8.5"

      - name: Prepare building environment
        run: make prepare

      - name: Run checks
        run: make check

      - name: Run tests
        run: make test

      - name: Build standalone binary
        run: make build

      - name: Smoke test binary --help
        run: ./dist/kimi --help

      - name: Upload binary artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: kimi-${{ matrix.target }}
          path: dist/kimi
          if-no-files-found: error
          retention-days: 7
